# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(Build.SourceVersion)
  displayName: 'Print Build.SourceVersion'

- bash: |
    sha=$(git log --format=%B -n 1 $(Build.SourceVersion) | awk '{print $2}')
    echo "##vso[task.setvariable variable=HeadVersion]$sha"
  displayName: 'set HeadVersion'

- script: echo $(HeadVersion)
  displayName: 'Print HeadVersion'
